# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "You will never know what you can do till you try"

description: "universeroc"
author:
  name: "universeroc"
  email: universeroc@gmail.com
  github: universeroc
  twitter: "#"
  pinterest: universeroc
  linkedin: universeroc
  bio: You will never know what you can do till you try
  avatar: assets/media/avatar.png
  avatar35: assets/media/avatar35.png

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
