# Site settings
title: You will never know what you can do till you try

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://yupengzhang.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true
